fieldLayouts:
  81f8eafa-a3a0-49e9-95e2-9f0bf658bbcb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1c302d41-7d88-4250-b6b4-827acdce4036
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a57f9432-0b15-4d7e-8858-de12f580b77d # banner-title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f7e7faf-6a7e-43b6-b6b3-37217916e2ee
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0b6d56ad-e595-4257-beb0-51f656d25b5f # banner-text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 39daa3df-f8b5-4aac-a1bf-ca124ef3fbe6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fa869fbb-80de-4b07-8481-3fd886e5b5fd # banner-image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8cbfdc7-8085-4a4a-948f-73e2f125e15e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7a8f7089-fb32-4004-8b9c-8db0cd0fcfd2
        userCondition: null
handle: homepage
hasTitleField: false
name: homepage
section: b1cf72e9-894e-4b31-b5b6-8ba04d1479cb # homepage
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
