fieldLayouts:
  fb3abb23-8540-4b11-8ee1-261f4a8d9f48:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: b6b65f80-16c8-4edc-941c-88513f1dbbe2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 56f32c3a-b28d-421d-acd2-85c2e79f4941
        userCondition: null
fs: companyAssets
handle: companyAssets
name: 'company assets'
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: assets
transformSubpath: ''
