columnSuffix: null
contentColumnType: string
fieldGroup: 37ebbc70-0c96-4509-8d2d-aadb391c7698 # products
handle: productImage
instructions: 'image of the product'
name: product-image
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  branchLimit: null
  defaultUploadLocationSource: 'volume:93bf6a67-dde7-4bbb-ab2b-8c04d8ea98b7' # product-assets
  defaultUploadLocationSubpath: '/{slug}'
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:93bf6a67-dde7-4bbb-ab2b-8c04d8ea98b7' # product-assets
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
      -
        - conditionRules
        -
          -
            __assoc__:
              -
                - class
                - craft\elements\conditions\assets\HeightConditionRule
              -
                - uid
                - a2ee95a7-a909-4050-96b6-292897b65787
              -
                - operator
                - '='
              -
                - value
                - '300'
              -
                - maxValue
                - ''
  selectionLabel: null
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
