dateModified: 1704216749
elementSources:
  craft\elements\Entry:
    -
      key: '*'
      type: native
    -
      heading: Channels
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:4d1124c1-bb8f-4029-a0e9-4c270757cdeb' # products
      tableAttributes:
        - postDate
        - expiryDate
        - link
        - 'field:8b83c4e8-99d9-4e85-a43c-b88a98c20c84' # product-price
        - 'field:2d4821a0-b7c7-40da-936b-491c1cb092a6' # product-image
      type: native
    -
      heading: ''
      type: heading
    -
      defaultSort:
        - title
        - asc
      disabled: false
      key: singles
      tableAttributes:
        - link
        - 'field:95690630-5893-4b1f-9b63-8aaacf90435f' # company-image
      type: native
email:
  fromEmail: milana_is@hotmail.com
  fromName: 'sport catalogus'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  assets:
    hasUrls: true
    name: assets
    settings:
      path: '@webroot'
    type: craft\fs\Local
    url: '@web'
  companyAssets:
    hasUrls: true
    name: 'company assets'
    settings:
      path: '@webroot'
    type: craft\fs\Local
    url: '@web'
meta:
  __names__:
    0b6d56ad-e595-4257-beb0-51f656d25b5f: banner-text # banner-text
    0c4ace3d-c87d-498a-810c-a48709d3873f: 'image preview' # image preview
    0eeb7a7a-ae99-4cbd-9aa6-3d4dfb955303: homepage # homepage
    1c1c07ac-ae0c-4475-9d7d-d1573f81ee71: product-category # product-category
    2d4821a0-b7c7-40da-936b-491c1cb092a6: product-image # product-image
    4d1124c1-bb8f-4029-a0e9-4c270757cdeb: products # products
    06c63463-001c-4e31-8ae1-4796a44815cf: 'sport catalogus' # sport catalogus
    7b0d5659-26a5-4a11-b19d-c448d53df442: 'company assets' # company assets
    8b83c4e8-99d9-4e85-a43c-b88a98c20c84: product-price # product-price
    8d263b6f-6746-4359-8556-8a29a6ab594c: mobilePreview # mobilePreview
    9a6d205c-50a0-42fa-9881-d3bec5eaf967: header # header
    9ecb36cc-29f4-4826-bb99-2704a87a5fea: Common # Common
    37ebbc70-0c96-4509-8d2d-aadb391c7698: products # products
    53bf9987-2148-4aa0-86bb-71fde34f4604: Default # Default
    93bf6a67-dde7-4bbb-ab2b-8c04d8ea98b7: product-assets # product-assets
    8347fa13-8ec9-4b96-84fd-ca08ea7dc0e7: header # header
    680398ac-9609-446c-8066-374815c5b013: 'sport catalogus' # sport catalogus
    747070c2-a654-448c-901d-7a75e1c8c8ed: categories # categories
    25666555-7000-4c52-987a-b5e6de861c5c: 'logo preview' # logo preview
    95690630-5893-4b1f-9b63-8aaacf90435f: company-image # company-image
    a57f9432-0b15-4d7e-8858-de12f580b77d: banner-title # banner-title
    ae2f83f2-c4f9-4ee6-b2aa-75d373bb2710: header # header
    b1cf72e9-894e-4b31-b5b6-8ba04d1479cb: homepage # homepage
    e009e9f0-3cd4-487e-89a0-b249443e4705: 'product categories' # product categories
    fa869fbb-80de-4b07-8481-3fd886e5b5fd: banner-image # banner-image
plugins:
  breadcrumb:
    edition: standard
    enabled: true
    schemaVersion: 1.1.1
  currency-converter:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  sprig:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
system:
  edition: solo
  live: true
  name: 'sport catalogus'
  schemaVersion: 4.5.3.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
