defaultPlacement: end
enableVersioning: true
handle: products
name: products
propagationMethod: all
siteSettings:
  06c63463-001c-4e31-8ae1-4796a44815cf: # sport catalogus
    enabledByDefault: true
    hasUrls: true
    template: products/_entry
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: e4245033-850e-4ed4-aea1-ac0d55181a01
type: structure
